### ISSUE TITLE
Unable to import module on case-sensitive file systems (ie. wsl)

### ISSUE THREAD

**Issue by jasonchester** [mazzy-ax/Write-ProgressEx#5]
On the windows subsystem for linux or any other system running powershell core, Write-ProgressEx is unable to be imported.

This appears to be due to the name of the module in PSGallery being **write-ProgressEx** instead of **Write-ProgressEx**

These issues seem to be relevant.
* https://github.com/PowerShell/PowerShell/issues/1621
* https://github.com/PowerShell/PowerShell/issues/706

I was able to work around the issue by renaming the module folder from write-ProgressEx to Write-ProgressEx after install.
```Powershell
PS /home/jchester> Install-Module write-ProgressEx -Verbose
PS /home/jchester> Get-Module -ListAvailable *ProgressEx #returns nothing
PS /home/jchester> mv /usr/local/share/powershell/Modules/write-ProgressEx/ /usr/local/share/powershell/Modules/Write-ProgressEx
PS /home/jchester> Get-Module -ListAvailable *ProgressEx

    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     0.20       Write-ProgressEx                    Desk      {Write-ProgressEx, Get-ProgressEx, Set-ProgressEx}

```

**Comment by mazzy-ax** [comment]
The Microsoft PowershellGallery team have changed the name.
https://www.powershellgallery.com/packages/Write-ProgressEx

jasonchester, thanks to you!
